// Code generated by MockGen. DO NOT EDIT.
// Source: ingestor.go
//
// Generated by this command:
//
//	mockgen -source=ingestor.go -destination=mocks/mock_ingestor.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "e2e-framework/internal/core/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageIngestor is a mock of MessageIngestor interface.
type MockMessageIngestor struct {
	ctrl     *gomock.Controller
	recorder *MockMessageIngestorMockRecorder
	isgomock struct{}
}

// MockMessageIngestorMockRecorder is the mock recorder for MockMessageIngestor.
type MockMessageIngestorMockRecorder struct {
	mock *MockMessageIngestor
}

// NewMockMessageIngestor creates a new mock instance.
func NewMockMessageIngestor(ctrl *gomock.Controller) *MockMessageIngestor {
	mock := &MockMessageIngestor{ctrl: ctrl}
	mock.recorder = &MockMessageIngestorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageIngestor) EXPECT() *MockMessageIngestorMockRecorder {
	return m.recorder
}

// Ingest mocks base method.
func (m *MockMessageIngestor) Ingest(ctx context.Context, msg *domain.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ingest", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ingest indicates an expected call of Ingest.
func (mr *MockMessageIngestorMockRecorder) Ingest(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ingest", reflect.TypeOf((*MockMessageIngestor)(nil).Ingest), ctx, msg)
}
