// Code generated by MockGen. DO NOT EDIT.
// Source: imap_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"
	domain "e2e-framework/internal/core/domain"
	"reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockIMAPClient struct {
	ctrl     *gomock.Controller
	recorder *MockIMAPClientMockRecorder
	isgomock struct{}
}

type MockIMAPClientMockRecorder struct {
	mock *MockIMAPClient
}

func NewMockIMAPClient(ctrl *gomock.Controller) *MockIMAPClient {
	mock := &MockIMAPClient{ctrl: ctrl}
	mock.recorder = &MockIMAPClientMockRecorder{mock}

	return mock
}

func (m *MockIMAPClient) EXPECT() *MockIMAPClientMockRecorder {
	return m.recorder
}

func (m *MockIMAPClient) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)

	return ret0
}

func (mr *MockIMAPClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockIMAPClient)(nil).Connect))
}

func (m *MockIMAPClient) SearchByRunID(ctx context.Context, runID string) (*domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByRunID", ctx, runID)
	ret0, _ := ret[0].(*domain.Message)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

func (mr *MockIMAPClientMockRecorder) SearchByRunID(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByRunID", reflect.TypeOf((*MockIMAPClient)(nil).SearchByRunID), ctx, runID)
}

func (m *MockIMAPClient) Disconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect")
	ret0, _ := ret[0].(error)

	return ret0
}

func (mr *MockIMAPClientMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockIMAPClient)(nil).Disconnect))
}
