// Code generated by MockGen. DO NOT EDIT.
// Source: assertion.go
//
// Generated by this command:
//
//	mockgen -source=assertion.go -destination=mocks/mock_assertion.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "e2e-framework/internal/core/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAssertion is a mock of Assertion interface.
type MockAssertion struct {
	ctrl     *gomock.Controller
	recorder *MockAssertionMockRecorder
	isgomock struct{}
}

// MockAssertionMockRecorder is the mock recorder for MockAssertion.
type MockAssertionMockRecorder struct {
	mock *MockAssertion
}

// NewMockAssertion creates a new mock instance.
func NewMockAssertion(ctrl *gomock.Controller) *MockAssertion {
	mock := &MockAssertion{ctrl: ctrl}
	mock.recorder = &MockAssertionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssertion) EXPECT() *MockAssertionMockRecorder {
	return m.recorder
}

// Assert mocks base method.
func (m *MockAssertion) Assert(msg *domain.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assert", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assert indicates an expected call of Assert.
func (mr *MockAssertionMockRecorder) Assert(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assert", reflect.TypeOf((*MockAssertion)(nil).Assert), msg)
}
