// Code generated by MockGen. DO NOT EDIT.
// Source: imap_client.go
//
// Generated by this command:
//
//	mockgen -source=imap_client.go -destination=mocks/mock_imap_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "e2e-framework/internal/core/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIMAPClient is a mock of IMAPClient interface.
type MockIMAPClient struct {
	ctrl     *gomock.Controller
	recorder *MockIMAPClientMockRecorder
	isgomock struct{}
}

// MockIMAPClientMockRecorder is the mock recorder for MockIMAPClient.
type MockIMAPClientMockRecorder struct {
	mock *MockIMAPClient
}

// NewMockIMAPClient creates a new mock instance.
func NewMockIMAPClient(ctrl *gomock.Controller) *MockIMAPClient {
	mock := &MockIMAPClient{ctrl: ctrl}
	mock.recorder = &MockIMAPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMAPClient) EXPECT() *MockIMAPClientMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockIMAPClient) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockIMAPClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockIMAPClient)(nil).Connect))
}

// Disconnect mocks base method.
func (m *MockIMAPClient) Disconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockIMAPClientMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockIMAPClient)(nil).Disconnect))
}

// SearchByRunID mocks base method.
func (m *MockIMAPClient) SearchByRunID(ctx context.Context, runID string) (*domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByRunID", ctx, runID)
	ret0, _ := ret[0].(*domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByRunID indicates an expected call of SearchByRunID.
func (mr *MockIMAPClientMockRecorder) SearchByRunID(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByRunID", reflect.TypeOf((*MockIMAPClient)(nil).SearchByRunID), ctx, runID)
}
